### ISSUE TITLE
Add a modal for successfully completion of the event. 

### ISSUE THREAD

**Issue by vinitvijal** [vinitvijal/CodeMystique-Hackathon-Website#2]
You must create a modal without interfering with any other files or jsx;
You must make use of Tailwind.

**Comment by acmsscbs** [comment]
I want to work on this issue. Please assign it to me @vinitvijal

**Comment by 7sumona02** [comment]
I want to work on this issue. Please assign it to me @vinitvijal.

**Comment by Senor-DPM** [comment]
I want to work on this issue. Please assign it to me @vinitvijal

**Comment by Roshniy-37** [comment]
I want to work on the issue. Please assign it to me @vinitvijal.

**Comment by Deepali2504** [comment]
I want to work on the issue. Please assign it to me @vinitvijal

**Comment by 1harshit123** [comment]
i want to work on the issue. please assign it to me @vinitvijal

**Comment by vinitvijal** [comment]
Completed by @7sumona02
